//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIETHUYVE
    {
        public string MAHD { get; set; }
        public string MAYEUCAU { get; set; }
        public Nullable<System.DateTime> NGAYHUY { get; set; }
        public Nullable<double> SOTIENHOANLAI { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual HUYDOIVE HUYDOIVE { get; set; }
    }
}
