//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUCVU
    {
        public CHUCVU()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public int MACV { get; set; }
        public string TENCHUCVU { get; set; }
    
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
    }
}
