//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DICHVU
    {
        public DICHVU()
        {
            this.CHITIETHOADONDICHVUs = new HashSet<CHITIETHOADONDICHVU>();
        }
    
        public string MADV { get; set; }
        public string TENDV { get; set; }
        public string LOAIDV { get; set; }
        public string MOTA { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<double> GIADV { get; set; }
    
        public virtual ICollection<CHITIETHOADONDICHVU> CHITIETHOADONDICHVUs { get; set; }
    }
}
