//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GHE()
        {
            this.CHITIETDATVEs = new HashSet<CHITIETDATVE>();
        }
    
        public string MAGHE { get; set; }
        public string MAPHONG { get; set; }
        public string LOAIGHE { get; set; }
        public string DAYGHE { get; set; }
        public Nullable<decimal> PHUPHI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATVE> CHITIETDATVEs { get; set; }
        public virtual PHONGCHIEU PHONGCHIEU { get; set; }
    }
}
