//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GHE
    {
        public GHE()
        {
            this.CHITIETDATVEs = new HashSet<CHITIETDATVE>();
            this.TINHTRANGGHEs = new HashSet<TINHTRANGGHE>();
        }
    
        public string MAGHE { get; set; }
        public string MAPHONG { get; set; }
        public string LOAIGHE { get; set; }
        public string DAYGHE { get; set; }
        public Nullable<double> PHUPHI { get; set; }
    
        public virtual ICollection<CHITIETDATVE> CHITIETDATVEs { get; set; }
        public virtual PHONGCHIEU PHONGCHIEU { get; set; }
        public virtual ICollection<TINHTRANGGHE> TINHTRANGGHEs { get; set; }
    }
}
