//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HUYDOIVE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HUYDOIVE()
        {
            this.CHITIETHUYVEs = new HashSet<CHITIETHUYVE>();
        }
    
        public string MAYEUCAU { get; set; }
        public Nullable<System.DateTime> NGAYYEUCAU { get; set; }
        public string LOAIYEUCAU { get; set; }
        public string LYDO { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETHUYVE> CHITIETHUYVEs { get; set; }
    }
}
