//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHUYENMAI
    {
        public KHUYENMAI()
        {
            this.CHITIETKHUYENMAIs = new HashSet<CHITIETKHUYENMAI>();
        }
    
        public string MAKM { get; set; }
        public string TENKM { get; set; }
        public string LOAIKM { get; set; }
        public Nullable<System.DateTime> NGAYBD { get; set; }
        public Nullable<System.DateTime> NGAYKT { get; set; }
        public string DIEUKIEN { get; set; }
    
        public virtual ICollection<CHITIETKHUYENMAI> CHITIETKHUYENMAIs { get; set; }
    }
}
