//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHIM
    {
        public PHIM()
        {
            this.SUATCHIEUx = new HashSet<SUATCHIEU>();
        }
    
        public string MAPHIM { get; set; }
        public string TENPHIM { get; set; }
        public string NHASANXUAT { get; set; }
        public string THELOAI { get; set; }
        public Nullable<int> THOILUONG { get; set; }
        public string NGONNGU { get; set; }
        public string DINHDANG { get; set; }
        public Nullable<System.DateTime> NGAYPH { get; set; }
        public string TRANGTHAI { get; set; }
        public string MOTA { get; set; }
        public string POSTER { get; set; }
        public string TRAILER { get; set; }
        public string DOTUOI { get; set; }
        public string DIENVIEN { get; set; }
    
        public virtual ICollection<SUATCHIEU> SUATCHIEUx { get; set; }
    }
}
