//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGCHIEU
    {
        public PHONGCHIEU()
        {
            this.GHEs = new HashSet<GHE>();
            this.SUATCHIEUx = new HashSet<SUATCHIEU>();
        }
    
        public string MAPHONG { get; set; }
        public string MARAP { get; set; }
        public Nullable<int> SUCCHUA { get; set; }
        public string MALOAI { get; set; }
    
        public virtual ICollection<GHE> GHEs { get; set; }
        public virtual LOAIMANHINH LOAIMANHINH { get; set; }
        public virtual RAP RAP { get; set; }
        public virtual ICollection<SUATCHIEU> SUATCHIEUx { get; set; }
    }
}
