//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class QLDATVEEntities : DbContext
    {
        public QLDATVEEntities()
            : base("name=QLDATVEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CHITIETDATVE> CHITIETDATVEs { get; set; }
        public virtual DbSet<CHITIETHOADONDICHVU> CHITIETHOADONDICHVUs { get; set; }
        public virtual DbSet<CHITIETHUYVE> CHITIETHUYVEs { get; set; }
        public virtual DbSet<CHITIETKHUYENMAI> CHITIETKHUYENMAIs { get; set; }
        public virtual DbSet<CHUCVU> CHUCVUs { get; set; }
        public virtual DbSet<DICHVU> DICHVUs { get; set; }
        public virtual DbSet<GHE> GHEs { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
        public virtual DbSet<HUYDOIVE> HUYDOIVEs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public virtual DbSet<LOAIMANHINH> LOAIMANHINHs { get; set; }
        public virtual DbSet<PHIEUTHANHTOAN> PHIEUTHANHTOANs { get; set; }
        public virtual DbSet<PHIM> PHIMs { get; set; }
        public virtual DbSet<PHONGCHIEU> PHONGCHIEUx { get; set; }
        public virtual DbSet<PHUONGTHUCTHANHTOAN> PHUONGTHUCTHANHTOANs { get; set; }
        public virtual DbSet<RAP> RAPs { get; set; }
        public virtual DbSet<SUATCHIEU> SUATCHIEUx { get; set; }
        public virtual DbSet<TINHTRANGGHE> TINHTRANGGHEs { get; set; }
        public virtual DbSet<VE> VEs { get; set; }
    
        public virtual ObjectResult<Nullable<int>> GiuGheTamThoi(string danhSachMaGhe, string maSuatChieu, string mAKH, string maGiuGhe)
        {
            var danhSachMaGheParameter = danhSachMaGhe != null ?
                new ObjectParameter("DanhSachMaGhe", danhSachMaGhe) :
                new ObjectParameter("DanhSachMaGhe", typeof(string));
    
            var maSuatChieuParameter = maSuatChieu != null ?
                new ObjectParameter("MaSuatChieu", maSuatChieu) :
                new ObjectParameter("MaSuatChieu", typeof(string));
    
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            var maGiuGheParameter = maGiuGhe != null ?
                new ObjectParameter("MaGiuGhe", maGiuGhe) :
                new ObjectParameter("MaGiuGhe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("GiuGheTamThoi", danhSachMaGheParameter, maSuatChieuParameter, mAKHParameter, maGiuGheParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> HuyGheHetHan(string maSuatChieu)
        {
            var maSuatChieuParameter = maSuatChieu != null ?
                new ObjectParameter("MaSuatChieu", maSuatChieu) :
                new ObjectParameter("MaSuatChieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("HuyGheHetHan", maSuatChieuParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> HuyGiuGhe(string maGiuGhe, string mAKH)
        {
            var maGiuGheParameter = maGiuGhe != null ?
                new ObjectParameter("MaGiuGhe", maGiuGhe) :
                new ObjectParameter("MaGiuGhe", typeof(string));
    
            var mAKHParameter = mAKH != null ?
                new ObjectParameter("MAKH", mAKH) :
                new ObjectParameter("MAKH", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("HuyGiuGhe", maGiuGheParameter, mAKHParameter);
        }
    
        public virtual ObjectResult<Nullable<int>> KiemTraTrangThaiGhe(string danhSachMaGhe, string maSuatChieu)
        {
            var danhSachMaGheParameter = danhSachMaGhe != null ?
                new ObjectParameter("DanhSachMaGhe", danhSachMaGhe) :
                new ObjectParameter("DanhSachMaGhe", typeof(string));
    
            var maSuatChieuParameter = maSuatChieu != null ?
                new ObjectParameter("MaSuatChieu", maSuatChieu) :
                new ObjectParameter("MaSuatChieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<int>>("KiemTraTrangThaiGhe", danhSachMaGheParameter, maSuatChieuParameter);
        }
    
        public virtual ObjectResult<LayDanhSachGhe_Result> LayDanhSachGhe(string maSuatChieu)
        {
            var maSuatChieuParameter = maSuatChieu != null ?
                new ObjectParameter("MaSuatChieu", maSuatChieu) :
                new ObjectParameter("MaSuatChieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayDanhSachGhe_Result>("LayDanhSachGhe", maSuatChieuParameter);
        }
    
        public virtual ObjectResult<LayThongTinGhe_Result> LayThongTinGhe(string danhSachMaGhe)
        {
            var danhSachMaGheParameter = danhSachMaGhe != null ?
                new ObjectParameter("DanhSachMaGhe", danhSachMaGhe) :
                new ObjectParameter("DanhSachMaGhe", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<LayThongTinGhe_Result>("LayThongTinGhe", danhSachMaGheParameter);
        }
    
        public virtual int SinhGheChoPhong(string maPhong)
        {
            var maPhongParameter = maPhong != null ?
                new ObjectParameter("MaPhong", maPhong) :
                new ObjectParameter("MaPhong", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SinhGheChoPhong", maPhongParameter);
        }
    
        public virtual int SinhTinhTrangGhe_All(string maSuatChieu)
        {
            var maSuatChieuParameter = maSuatChieu != null ?
                new ObjectParameter("MaSuatChieu", maSuatChieu) :
                new ObjectParameter("MaSuatChieu", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SinhTinhTrangGhe_All", maSuatChieuParameter);
        }
    
        public virtual int sp_UpdateNgayChieuTheoKhoang(Nullable<int> tu, Nullable<int> den, Nullable<System.DateTime> ngayChieu)
        {
            var tuParameter = tu.HasValue ?
                new ObjectParameter("Tu", tu) :
                new ObjectParameter("Tu", typeof(int));
    
            var denParameter = den.HasValue ?
                new ObjectParameter("Den", den) :
                new ObjectParameter("Den", typeof(int));
    
            var ngayChieuParameter = ngayChieu.HasValue ?
                new ObjectParameter("NgayChieu", ngayChieu) :
                new ObjectParameter("NgayChieu", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_UpdateNgayChieuTheoKhoang", tuParameter, denParameter, ngayChieuParameter);
        }
    
        public virtual ObjectResult<ThanhToan_Result> ThanhToan(string maGiuGhe, string maKhachHang, string maSuatChieu, Nullable<decimal> tongTien)
        {
            var maGiuGheParameter = maGiuGhe != null ?
                new ObjectParameter("MaGiuGhe", maGiuGhe) :
                new ObjectParameter("MaGiuGhe", typeof(string));
    
            var maKhachHangParameter = maKhachHang != null ?
                new ObjectParameter("MaKhachHang", maKhachHang) :
                new ObjectParameter("MaKhachHang", typeof(string));
    
            var maSuatChieuParameter = maSuatChieu != null ?
                new ObjectParameter("MaSuatChieu", maSuatChieu) :
                new ObjectParameter("MaSuatChieu", typeof(string));
    
            var tongTienParameter = tongTien.HasValue ?
                new ObjectParameter("TongTien", tongTien) :
                new ObjectParameter("TongTien", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ThanhToan_Result>("ThanhToan", maGiuGheParameter, maKhachHangParameter, maSuatChieuParameter, tongTienParameter);
        }
    
        public virtual ObjectResult<TraCuuLichChieu_Result> TraCuuLichChieu(Nullable<System.DateTime> ngayChieu, string maLoai, string diaChi, string maPhim)
        {
            var ngayChieuParameter = ngayChieu.HasValue ?
                new ObjectParameter("NgayChieu", ngayChieu) :
                new ObjectParameter("NgayChieu", typeof(System.DateTime));
    
            var maLoaiParameter = maLoai != null ?
                new ObjectParameter("MaLoai", maLoai) :
                new ObjectParameter("MaLoai", typeof(string));
    
            var diaChiParameter = diaChi != null ?
                new ObjectParameter("DiaChi", diaChi) :
                new ObjectParameter("DiaChi", typeof(string));
    
            var maPhimParameter = maPhim != null ?
                new ObjectParameter("MaPhim", maPhim) :
                new ObjectParameter("MaPhim", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<TraCuuLichChieu_Result>("TraCuuLichChieu", ngayChieuParameter, maLoaiParameter, diaChiParameter, maPhimParameter);
        }
    }
}
