//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLDATVEEntities : DbContext
    {
        public QLDATVEEntities()
            : base("name=QLDATVEEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CHITIETDATVE> CHITIETDATVEs { get; set; }
        public DbSet<CHITIETHOADONDICHVU> CHITIETHOADONDICHVUs { get; set; }
        public DbSet<CHITIETHUYVE> CHITIETHUYVEs { get; set; }
        public DbSet<CHITIETKHUYENMAI> CHITIETKHUYENMAIs { get; set; }
        public DbSet<DICHVU> DICHVUs { get; set; }
        public DbSet<GHE> GHEs { get; set; }
        public DbSet<HOADON> HOADONs { get; set; }
        public DbSet<HUYDOIVE> HUYDOIVEs { get; set; }
        public DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public DbSet<KHUYENMAI> KHUYENMAIs { get; set; }
        public DbSet<LOAIMANHINH> LOAIMANHINHs { get; set; }
        public DbSet<PHIEUTHANHTOAN> PHIEUTHANHTOANs { get; set; }
        public DbSet<PHIM> PHIMs { get; set; }
        public DbSet<PHONGCHIEU> PHONGCHIEUx { get; set; }
        public DbSet<PHUONGTHUCTHANHTOAN> PHUONGTHUCTHANHTOANs { get; set; }
        public DbSet<RAP> RAPs { get; set; }
        public DbSet<SUATCHIEU> SUATCHIEUx { get; set; }
        public DbSet<TINHTRANGGHE> TINHTRANGGHEs { get; set; }
        public DbSet<VE> VEs { get; set; }
    }
}
