//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RAP
    {
        public RAP()
        {
            this.PHONGCHIEUx = new HashSet<PHONGCHIEU>();
            this.SUATCHIEUx = new HashSet<SUATCHIEU>();
        }
    
        public string MARAP { get; set; }
        public string TENRAP { get; set; }
        public string DIACHI { get; set; }
    
        public virtual ICollection<PHONGCHIEU> PHONGCHIEUx { get; set; }
        public virtual ICollection<SUATCHIEU> SUATCHIEUx { get; set; }
    }
}
