//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUATCHIEU
    {
        public SUATCHIEU()
        {
            this.TINHTRANGGHEs = new HashSet<TINHTRANGGHE>();
        }
    
        public string MASUATCHIEU { get; set; }
        public string MAPHIM { get; set; }
        public string MARAP { get; set; }
        public string MAPHONG { get; set; }
        public Nullable<System.DateTime> NGAYCHIEU { get; set; }
        public Nullable<System.TimeSpan> GIOCHIEU { get; set; }
        public Nullable<double> GIACOBAN { get; set; }
        public string TRANGTHAI { get; set; }
    
        public virtual PHIM PHIM { get; set; }
        public virtual PHONGCHIEU PHONGCHIEU { get; set; }
        public virtual RAP RAP { get; set; }
        public virtual ICollection<TINHTRANGGHE> TINHTRANGGHEs { get; set; }
    }
}
