//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TINHTRANGGHE
    {
        public string MAGHE { get; set; }
        public string MASUATCHIEU { get; set; }
        public string TINHTRANG { get; set; }
    
        public virtual GHE GHE { get; set; }
        public virtual SUATCHIEU SUATCHIEU { get; set; }
    }
}
