//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dat_Ve_Xem_Phim_CGV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VE()
        {
            this.CHITIETDATVEs = new HashSet<CHITIETDATVE>();
        }
    
        public string MAVE { get; set; }
        public string MAHD { get; set; }
        public string MASUATCHIEU { get; set; }
        public string MAGHE { get; set; }
        public string MAPHONG { get; set; }
        public Nullable<decimal> GIAVE { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<System.DateTime> NGAYDATVE { get; set; }
        public Nullable<System.DateTime> CHECKIN { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETDATVE> CHITIETDATVEs { get; set; }
        public virtual HOADON HOADON { get; set; }
        public virtual SUATCHIEU SUATCHIEU { get; set; }
    }
}
